apiVersion: v1
kind: Service
metadata:
  name: {{ include "capstone-chart.fullname" . }}-capstone-deployment-loadbalancer
  labels:
    app: capstone-metrics-target
  {{- include "capstone-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.capstoneDeploymentLoadbalancer.type }}
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-capstone-capstone-deployment
    {{- include "capstone-chart.selectorLabels" . | nindent 4 }}
  {{- if .Values.capstoneDeploymentLoadbalancer.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.capstoneDeploymentLoadbalancer.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.capstoneDeploymentLoadbalancer.ipFamilies }}
  ipFamilies:
  {{- .Values.capstoneDeploymentLoadbalancer.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
  {{- .Values.capstoneDeploymentLoadbalancer.ports | toYaml | nindent 2 }}
